// Lista de estados y ciudades de USA con sus IDs de MegaPersonals (cid).
// El cid es necesario para que el bot pueda cambiar la ciudad en la edición:
// MegaPersonals usa el campo hidden #cityId (con el cid) NO #cityName (texto).
//
// Generado automáticamente desde el JSON de MegaPersonals.

export interface CityInfo {
  cid: number;
  name: string;
}

export interface StateInfo {
  abrev: string;
  ciudades: CityInfo[];
}

export const US_LOCATIONS: Record<string, StateInfo> = {
  "Alabama": { abrev: "AL", ciudades: [{ cid: 200, name: "Auburn" }, { cid: 77, name: "Birmingham" }, { cid: 201, name: "Dothan" }, { cid: 202, name: "Gadsden" }, { cid: 78, name: "Huntsville" }, { cid: 79, name: "Mobile" }, { cid: 80, name: "Montgomery" }, { cid: 203, name: "Muscle Shoals" }, { cid: 204, name: "Tuscaloosa" }] },
  "Alaska": { abrev: "AK", ciudades: [{ cid: 81, name: "Anchorage" }, { cid: 205, name: "Fairbanks" }, { cid: 206, name: "Juneau" }, { cid: 207, name: "Kenai Peninsula" }] },
  "Arizona": { abrev: "AZ", ciudades: [{ cid: 213, name: "Flagstaff" }, { cid: 208, name: "Mohave County" }, { cid: 27, name: "Phoenix" }, { cid: 209, name: "Prescott" }, { cid: 210, name: "Show Low" }, { cid: 211, name: "Sierra Vista" }, { cid: 82, name: "Tucson" }, { cid: 212, name: "Yuma" }] },
  "Arkansas": { abrev: "AR", ciudades: [{ cid: 83, name: "Fayetteville" }, { cid: 214, name: "Fort Smith" }, { cid: 215, name: "Jonesboro" }, { cid: 84, name: "Little Rock" }] },
  "California": { abrev: "CA", ciudades: [{ cid: 85, name: "Bakersfield" }, { cid: 216, name: "Chico" }, { cid: 540, name: "Concord" }, { cid: 86, name: "Fresno" }, { cid: 89, name: "Humboldt County" }, { cid: 217, name: "Imperial County" }, { cid: 220, name: "Inland Empire" }, { cid: 221, name: "Lancaster" }, { cid: 90, name: "Long Beach" }, { cid: 8, name: "Los Angeles" }, { cid: 218, name: "Mendocino" }, { cid: 219, name: "Merced" }, { cid: 87, name: "Modesto" }, { cid: 91, name: "Monterey" }, { cid: 92, name: "North Bay" }, { cid: 93, name: "Oakland" }, { cid: 15, name: "Orange County" }, { cid: 94, name: "Palm Springs" }, { cid: 222, name: "Redding" }, { cid: 44, name: "Sacramento" }, { cid: 48, name: "San Diego" }, { cid: 95, name: "San Fernando Valley" }, { cid: 6, name: "San Francisco" }, { cid: 223, name: "San Gabriel Valley" }, { cid: 96, name: "San Jose" }, { cid: 224, name: "San Luis Obispo" }, { cid: 97, name: "San Mateo" }, { cid: 225, name: "Santa Barbara" }, { cid: 98, name: "Santa Cruz" }, { cid: 226, name: "Santa Maria" }, { cid: 227, name: "Siskiyou" }, { cid: 88, name: "Stockton" }, { cid: 99, name: "Ventura" }, { cid: 100, name: "Visalia" }] },
  "Colorado": { abrev: "CO", ciudades: [{ cid: 101, name: "Boulder" }, { cid: 102, name: "Colorado Springs" }, { cid: 17, name: "Denver" }, { cid: 103, name: "Fort Collins" }, { cid: 228, name: "Pueblo" }, { cid: 229, name: "Rockies" }, { cid: 230, name: "Western Slope" }] },
  "Connecticut": { abrev: "CT", ciudades: [{ cid: 104, name: "Bridgeport" }, { cid: 105, name: "Eastern Connecticut" }, { cid: 106, name: "Hartford" }, { cid: 107, name: "New Haven" }, { cid: 108, name: "Northwest" }] },
  "Delaware": { abrev: "DE", ciudades: [{ cid: 538, name: "Dover" }, { cid: 539, name: "Milford" }, { cid: 537, name: "Wilmington" }] },
  "District of Columbia": { abrev: "DC", ciudades: [{ cid: 232, name: "Annandale" }, { cid: 231, name: "Northern Virginia" }, { cid: 233, name: "Southern Maryland" }, { cid: 51, name: "Washington" }] },
  "Florida": { abrev: "FL", ciudades: [{ cid: 109, name: "Daytona" }, { cid: 113, name: "Fort Lauderdale" }, { cid: 234, name: "Fort Myers" }, { cid: 235, name: "Gainesville" }, { cid: 236, name: "Jacksonville" }, { cid: 114, name: "Keys" }, { cid: 25, name: "Miami" }, { cid: 238, name: "Ocala" }, { cid: 239, name: "Okaloosa" }, { cid: 18, name: "Orlando" }, { cid: 110, name: "Palm Bay" }, { cid: 240, name: "Panama City" }, { cid: 241, name: "Pensacola" }, { cid: 242, name: "Sarasota" }, { cid: 111, name: "Space Coast" }, { cid: 243, name: "St. Augustine" }, { cid: 244, name: "Tallahassee" }, { cid: 50, name: "Tampa" }, { cid: 112, name: "Treasure Coast" }, { cid: 115, name: "West Palm Beach" }] },
  "Georgia": { abrev: "GA", ciudades: [{ cid: 245, name: "Albany" }, { cid: 246, name: "Athens" }, { cid: 12, name: "Atlanta" }, { cid: 116, name: "Augusta" }, { cid: 247, name: "Brunswick" }, { cid: 248, name: "Columbus" }, { cid: 117, name: "Macon" }, { cid: 249, name: "Northwest Georgia" }, { cid: 118, name: "Savannah" }, { cid: 250, name: "Statesboro" }, { cid: 251, name: "Valdosta" }] },
  "Hawaii": { abrev: "HI", ciudades: [{ cid: 252, name: "Big Island" }, { cid: 119, name: "Honolulu" }, { cid: 253, name: "Kauai" }, { cid: 254, name: "Maui" }] },
  "Idaho": { abrev: "ID", ciudades: [{ cid: 255, name: "Boise" }, { cid: 256, name: "East Idaho" }, { cid: 257, name: "Lewiston" }, { cid: 258, name: "Twin Falls" }] },
  "Illinois": { abrev: "IL", ciudades: [{ cid: 259, name: "Bloomington" }, { cid: 260, name: "Carbondale" }, { cid: 261, name: "Chambana" }, { cid: 32, name: "Chicago" }, { cid: 262, name: "Decatur" }, { cid: 263, name: "La Salle County" }, { cid: 264, name: "Mattoon" }, { cid: 265, name: "Peoria" }, { cid: 266, name: "Rockford" }, { cid: 267, name: "Springfield" }, { cid: 268, name: "Western Illinois" }] },
  "Indiana": { abrev: "IN", ciudades: [{ cid: 269, name: "Bloomington" }, { cid: 270, name: "Evansville" }, { cid: 271, name: "Ft Wayne" }, { cid: 29, name: "Indianapolis" }, { cid: 272, name: "Kokomo" }, { cid: 273, name: "Lafayette" }, { cid: 274, name: "Muncie" }, { cid: 275, name: "Richmond" }, { cid: 276, name: "South Bend" }, { cid: 277, name: "Terre Haute" }] },
  "Iowa": { abrev: "IA", ciudades: [{ cid: 278, name: "Ames" }, { cid: 279, name: "Cedar Rapids" }, { cid: 120, name: "Desmoines" }, { cid: 280, name: "Dubuque" }, { cid: 281, name: "Fort Dodge" }, { cid: 282, name: "Iowa City" }, { cid: 283, name: "Mason City" }, { cid: 284, name: "Quad Cities" }, { cid: 285, name: "Sioux City" }, { cid: 286, name: "Southeast Iowa" }, { cid: 287, name: "Waterloo" }] },
  "Kansas": { abrev: "KS", ciudades: [{ cid: 288, name: "Lawrence" }, { cid: 289, name: "Manhattan" }, { cid: 290, name: "Salina" }, { cid: 291, name: "Topeka" }, { cid: 121, name: "Wichita" }] },
  "Kentucky": { abrev: "KY", ciudades: [{ cid: 292, name: "Bowling Green" }, { cid: 293, name: "Eastern Kentucky" }, { cid: 294, name: "Lexington" }, { cid: 14, name: "Louisville" }, { cid: 295, name: "Owensboro" }, { cid: 296, name: "Western Kentucky" }] },
  "Louisiana": { abrev: "LA", ciudades: [{ cid: 297, name: "Alexandria" }, { cid: 122, name: "Baton Rouge" }, { cid: 622, name: "Hammond" }, { cid: 298, name: "Houma" }, { cid: 123, name: "Lafayette" }, { cid: 299, name: "Lake Charles" }, { cid: 300, name: "Monroe" }, { cid: 41, name: "New Orleans" }, { cid: 301, name: "Shreveport" }] },
  "Maine": { abrev: "ME", ciudades: [{ cid: 302, name: "Bangor" }, { cid: 303, name: "Lewiston-Auburn" }, { cid: 304, name: "Portland" }] },
  "Maryland": { abrev: "MD", ciudades: [{ cid: 305, name: "Annapolis" }, { cid: 19, name: "Baltimore" }, { cid: 306, name: "Cumberland Valley" }, { cid: 307, name: "Eastern Shore" }, { cid: 308, name: "Frederick" }, { cid: 309, name: "Western Maryland" }] },
  "Massachusetts": { abrev: "MA", ciudades: [{ cid: 23, name: "Boston" }, { cid: 310, name: "Brockton" }, { cid: 311, name: "Cape Cod" }, { cid: 312, name: "Lowell" }, { cid: 124, name: "South Coast" }, { cid: 313, name: "Springfield" }, { cid: 314, name: "Worcester" }] },
  "Michigan": { abrev: "MI", ciudades: [{ cid: 315, name: "Ann Arbor" }, { cid: 316, name: "Battle Creek" }, { cid: 317, name: "Central Michigan" }, { cid: 20, name: "Detroit" }, { cid: 318, name: "Flint" }, { cid: 319, name: "Grand Rapids" }, { cid: 320, name: "Holland" }, { cid: 321, name: "Jackson" }, { cid: 322, name: "Kalamazoo" }, { cid: 323, name: "Lansing" }, { cid: 324, name: "Monroe" }, { cid: 325, name: "Muskegon" }, { cid: 326, name: "Northern Michigan" }, { cid: 327, name: "Port Huron" }, { cid: 328, name: "Saginaw" }, { cid: 329, name: "Southwest Michigan" }, { cid: 330, name: "Upper Peninsula" }] },
  "Minnesota": { abrev: "MN", ciudades: [{ cid: 331, name: "Bemidji" }, { cid: 332, name: "Brainerd" }, { cid: 333, name: "Duluth" }, { cid: 334, name: "Mankato" }, { cid: 34, name: "Minneapolis" }, { cid: 335, name: "Rochester" }, { cid: 336, name: "St. Cloud" }] },
  "Mississippi": { abrev: "MS", ciudades: [{ cid: 125, name: "Biloxi" }, { cid: 337, name: "Hattiesburg" }, { cid: 126, name: "Jackson" }, { cid: 338, name: "Meridian" }, { cid: 339, name: "North Mississippi" }, { cid: 340, name: "Southwest Mississippi" }] },
  "Missouri": { abrev: "MO", ciudades: [{ cid: 341, name: "Columbia" }, { cid: 342, name: "Joplin" }, { cid: 33, name: "Kansas City" }, { cid: 343, name: "Kirksville" }, { cid: 344, name: "Lake Of The Ozarks" }, { cid: 46, name: "Saint Louis" }, { cid: 345, name: "Southeast Missouri" }, { cid: 346, name: "Springfield" }, { cid: 347, name: "St Joseph" }] },
  "Montana": { abrev: "MT", ciudades: [{ cid: 348, name: "Billings" }, { cid: 349, name: "Bozeman" }, { cid: 350, name: "Butte" }, { cid: 351, name: "Great Falls" }, { cid: 352, name: "Helena" }, { cid: 353, name: "Kalispell" }, { cid: 354, name: "Missoula" }] },
  "Nebraska": { abrev: "NE", ciudades: [{ cid: 355, name: "Grand Island" }, { cid: 356, name: "Lincoln" }, { cid: 357, name: "North Platte" }, { cid: 127, name: "Omaha" }, { cid: 358, name: "Scottsbluff" }] },
  "Nevada": { abrev: "NV", ciudades: [{ cid: 359, name: "Elko" }, { cid: 9, name: "Las Vegas" }, { cid: 42, name: "Reno" }, { cid: 566, name: "Virginia City" }] },
  "New Hampshire": { abrev: "NH", ciudades: [{ cid: 360, name: "Concord" }, { cid: 361, name: "Dover" }, { cid: 362, name: "Manchester" }, { cid: 363, name: "Nashua" }] },
  "New Jersey": { abrev: "NJ", ciudades: [{ cid: 128, name: "Central Jersey" }, { cid: 129, name: "Jersey Shore" }, { cid: 364, name: "North Jersey" }, { cid: 365, name: "South Jersey" }] },
  "New Mexico": { abrev: "NM", ciudades: [{ cid: 366, name: "Albuquerque" }, { cid: 367, name: "Clovis" }, { cid: 368, name: "Farmington" }, { cid: 369, name: "Las Cruces" }, { cid: 370, name: "Roswell" }, { cid: 371, name: "Santa Fe" }] },
  "New York": { abrev: "NY", ciudades: [{ cid: 130, name: "Albany" }, { cid: 372, name: "Binghamton" }, { cid: 373, name: "Bronx" }, { cid: 374, name: "Brooklyn" }, { cid: 28, name: "Buffalo" }, { cid: 375, name: "Catskills" }, { cid: 376, name: "Chautauqua" }, { cid: 377, name: "Elmira" }, { cid: 379, name: "Finger Lakes" }, { cid: 380, name: "Glens Falls" }, { cid: 381, name: "Hudson Valley" }, { cid: 382, name: "Ithaca" }, { cid: 40, name: "Long Island" }, { cid: 383, name: "Manhattan" }, { cid: 7, name: "New York" }, { cid: 384, name: "Oneonta" }, { cid: 385, name: "Plattsburgh" }, { cid: 386, name: "Potsdam" }, { cid: 387, name: "Queens" }, { cid: 388, name: "Rochester" }, { cid: 389, name: "Staten Island" }, { cid: 390, name: "Syracuse" }, { cid: 391, name: "Twin Tiers" }, { cid: 392, name: "Utica" }, { cid: 393, name: "Watertown" }, { cid: 394, name: "Westchester" }] },
  "North Carolina": { abrev: "NC", ciudades: [{ cid: 395, name: "Asheville" }, { cid: 396, name: "Boone" }, { cid: 131, name: "Charlotte" }, { cid: 397, name: "Eastern" }, { cid: 398, name: "Fayetteville" }, { cid: 132, name: "Greensboro" }, { cid: 399, name: "Hickory" }, { cid: 400, name: "High Point" }, { cid: 401, name: "Outer Banks" }, { cid: 38, name: "Raleigh" }, { cid: 402, name: "Raleigh-Durham" }, { cid: 403, name: "Wilmington" }, { cid: 404, name: "Winston-Salem" }] },
  "North Dakota": { abrev: "ND", ciudades: [{ cid: 405, name: "Bismarck" }, { cid: 406, name: "Fargo" }, { cid: 407, name: "Grand Forks" }, { cid: 408, name: "Minot" }] },
  "Ohio": { abrev: "OH", ciudades: [{ cid: 409, name: "Akron" }, { cid: 412, name: "Ashtabula" }, { cid: 413, name: "Athens" }, { cid: 421, name: "Cambridge" }, { cid: 414, name: "Chillicothe" }, { cid: 36, name: "Cincinnati" }, { cid: 39, name: "Cleveland" }, { cid: 43, name: "Columbus" }, { cid: 415, name: "Dayton" }, { cid: 411, name: "Findlay" }, { cid: 416, name: "Mansfield" }, { cid: 417, name: "Sandusky" }, { cid: 418, name: "Toledo" }, { cid: 419, name: "Tuscarawas County" }, { cid: 420, name: "Youngstown" }] },
  "Oklahoma": { abrev: "OK", ciudades: [{ cid: 422, name: "Lawton" }, { cid: 423, name: "Norman" }, { cid: 133, name: "Oklahoma City" }, { cid: 424, name: "Stillwater" }, { cid: 134, name: "Tulsa" }] },
  "Oregon": { abrev: "OR", ciudades: [{ cid: 425, name: "Bend" }, { cid: 426, name: "Corvallis" }, { cid: 427, name: "East Oregon" }, { cid: 428, name: "Eugene" }, { cid: 429, name: "Klamath Falls" }, { cid: 430, name: "Medford" }, { cid: 431, name: "Oregon Coast" }, { cid: 35, name: "Portland" }, { cid: 432, name: "Roseburg" }, { cid: 433, name: "Salem" }] },
  "Pennsylvania": { abrev: "PA", ciudades: [{ cid: 434, name: "Allentown" }, { cid: 435, name: "Altoona" }, { cid: 436, name: "Chambersburg" }, { cid: 437, name: "Erie" }, { cid: 438, name: "Harrisburg" }, { cid: 439, name: "Lancaster" }, { cid: 440, name: "Meadville" }, { cid: 441, name: "Penn State" }, { cid: 22, name: "Philadelphia" }, { cid: 31, name: "Pittsburgh" }, { cid: 442, name: "Poconos" }, { cid: 443, name: "Reading" }, { cid: 444, name: "Scranton" }, { cid: 445, name: "Williamsport" }, { cid: 446, name: "York" }] },
  "Rhode Island": { abrev: "RI", ciudades: [{ cid: 135, name: "Providence" }, { cid: 447, name: "Warwick" }] },
  "South Carolina": { abrev: "SC", ciudades: [{ cid: 136, name: "Charleston" }, { cid: 137, name: "Columbia" }, { cid: 448, name: "Florence" }, { cid: 138, name: "Greenville" }, { cid: 449, name: "Hilton Head" }, { cid: 450, name: "Myrtle Beach" }] },
  "South Dakota": { abrev: "SD", ciudades: [{ cid: 451, name: "Aberdeen" }, { cid: 452, name: "Pierre" }, { cid: 453, name: "Rapid City" }, { cid: 454, name: "Sioux Falls" }] },
  "Tennessee": { abrev: "TN", ciudades: [{ cid: 455, name: "Chattanooga" }, { cid: 456, name: "Clarksville" }, { cid: 457, name: "Cookeville" }, { cid: 458, name: "Johnson City" }, { cid: 459, name: "Knoxville" }, { cid: 21, name: "Memphis" }, { cid: 37, name: "Nashville" }, { cid: 460, name: "Tri-Cities" }] },
  "Texas": { abrev: "TX", ciudades: [{ cid: 461, name: "Abilene" }, { cid: 462, name: "Amarillo" }, { cid: 16, name: "Austin" }, { cid: 463, name: "Beaumont" }, { cid: 464, name: "Brownsville" }, { cid: 465, name: "College Station" }, { cid: 466, name: "Corpus Christi" }, { cid: 13, name: "Dallas" }, { cid: 467, name: "Del Rio" }, { cid: 468, name: "Denton" }, { cid: 469, name: "El Paso" }, { cid: 139, name: "Fort Worth" }, { cid: 470, name: "Galveston" }, { cid: 0, name: "Houston" }, { cid: 471, name: "Huntsville" }, { cid: 472, name: "Killeen" }, { cid: 473, name: "Laredo" }, { cid: 474, name: "Longview" }, { cid: 475, name: "Lubbock" }, { cid: 476, name: "Mcallen" }, { cid: 477, name: "Mid Cities" }, { cid: 478, name: "Odessa" }, { cid: 47, name: "San Antonio" }, { cid: 479, name: "San Marcos" }, { cid: 480, name: "Texarkana" }, { cid: 481, name: "Texoma" }, { cid: 482, name: "Tyler" }, { cid: 483, name: "Victoria" }, { cid: 484, name: "Waco" }, { cid: 485, name: "Wichita Falls" }] },
  "Utah": { abrev: "UT", ciudades: [{ cid: 486, name: "Logan" }, { cid: 487, name: "Ogden" }, { cid: 488, name: "Provo" }, { cid: 45, name: "Salt Lake City" }, { cid: 489, name: "St. George" }] },
  "Vermont": { abrev: "VT", ciudades: [{ cid: 490, name: "Burlington" }, { cid: 492, name: "Colchester" }, { cid: 491, name: "Essex" }] },
  "Virginia": { abrev: "VA", ciudades: [{ cid: 493, name: "Charlottesville" }, { cid: 494, name: "Chesapeake" }, { cid: 495, name: "Danville" }, { cid: 496, name: "Fredericksburg" }, { cid: 497, name: "Hampton" }, { cid: 498, name: "Harrisonburg" }, { cid: 499, name: "Lynchburg" }, { cid: 500, name: "New River Valley" }, { cid: 501, name: "Newport News" }, { cid: 140, name: "Norfolk" }, { cid: 502, name: "Portsmouth" }, { cid: 141, name: "Richmond" }, { cid: 503, name: "Roanoke" }, { cid: 504, name: "Southwest Virginia" }, { cid: 505, name: "Suffolk" }, { cid: 142, name: "Virginia Beach" }] },
  "Washington": { abrev: "WA", ciudades: [{ cid: 506, name: "Bellingham" }, { cid: 143, name: "Everett" }, { cid: 507, name: "Moses Lake" }, { cid: 508, name: "Mt. Vernon" }, { cid: 509, name: "Olympia" }, { cid: 510, name: "Pullman" }, { cid: 49, name: "Seattle" }, { cid: 511, name: "Spokane" }, { cid: 144, name: "Tacoma" }, { cid: 512, name: "Tri-Cities" }, { cid: 513, name: "Wenatchee" }, { cid: 514, name: "Yakima" }] },
  "West Virginia": { abrev: "WV", ciudades: [{ cid: 515, name: "Charleston" }, { cid: 516, name: "Huntington" }, { cid: 517, name: "Martinsburg" }, { cid: 518, name: "Morgantown" }, { cid: 519, name: "Parkersburg" }, { cid: 520, name: "Southern West Virginia" }, { cid: 521, name: "Wheeling" }] },
  "Wisconsin": { abrev: "WI", ciudades: [{ cid: 522, name: "Appleton" }, { cid: 523, name: "Eau Claire" }, { cid: 524, name: "Green Bay" }, { cid: 525, name: "Janesville" }, { cid: 526, name: "La Crosse" }, { cid: 527, name: "Madison" }, { cid: 30, name: "Milwaukee" }, { cid: 528, name: "Racine" }, { cid: 529, name: "Sheboygan" }, { cid: 530, name: "Wausau" }] },
  "Wyoming": { abrev: "WY", ciudades: [{ cid: 532, name: "Casper" }, { cid: 531, name: "Cheyenne" }, { cid: 533, name: "Laramie" }] },
};
