// Lista de estados y ciudades de USA (replicada de MegaPersonals).
// Usada en el modal selector de ubicación al editar un post.
// Refactor: extraído de page.tsx para mejor organización.

export const US_LOCATIONS: Record<string, { abrev: string; ciudades: string[] }> = {
  "Alabama": { abrev: "AL", ciudades: ["Auburn","Birmingham","Dothan","Gadsden","Huntsville","Mobile","Montgomery","Muscle Shoals","Tuscaloosa"] },
  "Alaska": { abrev: "AK", ciudades: ["Anchorage","Fairbanks","Juneau","Kenai Peninsula"] },
  "Arizona": { abrev: "AZ", ciudades: ["Flagstaff","Mohave County","Phoenix","Prescott","Show Low","Sierra Vista","Tucson","Yuma"] },
  "Arkansas": { abrev: "AR", ciudades: ["Fayetteville","Fort Smith","Jonesboro","Little Rock"] },
  "California": { abrev: "CA", ciudades: ["Bakersfield","Chico","Concord","Fresno","Humboldt County","Imperial County","Inland Empire","Lancaster","Long Beach","Los Angeles","Mendocino","Merced","Modesto","Monterey","North Bay","Oakland","Orange County","Palm Springs","Redding","Sacramento","San Diego","San Fernando Valley","San Francisco","San Gabriel Valley","San Jose","San Luis Obispo","San Mateo","Santa Barbara","Santa Cruz","Santa Maria","Siskiyou","Stockton","Ventura","Visalia"] },
  "Colorado": { abrev: "CO", ciudades: ["Boulder","Colorado Springs","Denver","Fort Collins","Pueblo","Rockies","Western Slope"] },
  "Connecticut": { abrev: "CT", ciudades: ["Bridgeport","Eastern Connecticut","Hartford","New Haven","Northwest"] },
  "Delaware": { abrev: "DE", ciudades: ["Dover","Milford","Wilmington"] },
  "District of Columbia": { abrev: "DC", ciudades: ["Annandale","Northern Virginia","Southern Maryland"] },
  "Florida": { abrev: "FL", ciudades: ["Daytona","Fort Lauderdale","Fort Myers","Gainesville","Jacksonville","Keys","Miami","Ocala","Okaloosa","Orlando","Palm Bay","Panama City","Pensacola","Sarasota","Space Coast","St. Augustine","Tallahassee","Tampa","Treasure Coast","West Palm Beach"] },
  "Georgia": { abrev: "GA", ciudades: ["Albany","Athens","Atlanta","Augusta","Brunswick","Columbus","Macon","Northwest Georgia","Savannah","Statesboro","Valdosta"] },
  "Hawaii": { abrev: "HI", ciudades: ["Big Island","Honolulu","Kauai","Maui"] },
  "Idaho": { abrev: "ID", ciudades: ["Boise","East Idaho","Lewiston","Twin Falls"] },
  "Illinois": { abrev: "IL", ciudades: ["Bloomington","Carbondale","Chambana","Chicago","Decatur","La Salle County","Mattoon","Peoria","Rockford","Springfield","Western Illinois"] },
  "Indiana": { abrev: "IN", ciudades: ["Bloomington","Evansville","Ft Wayne","Indianapolis","Kokomo","Lafayette","Muncie","Richmond","South Bend","Terre Haute"] },
  "Iowa": { abrev: "IA", ciudades: ["Ames","Cedar Rapids","Desmoines","Dubuque","Fort Dodge","Iowa City","Mason City","Quad Cities","Sioux City","Southeast Iowa","Waterloo"] },
  "Kansas": { abrev: "KS", ciudades: ["Lawrence","Manhattan","Salina","Topeka","Wichita"] },
  "Kentucky": { abrev: "KY", ciudades: ["Bowling Green","Eastern Kentucky","Lexington","Louisville","Owensboro","Western Kentucky"] },
  "Louisiana": { abrev: "LA", ciudades: ["Alexandria","Baton Rouge","Hammond","Houma","Lafayette","Lake Charles","Monroe","New Orleans","Shreveport"] },
  "Maine": { abrev: "ME", ciudades: ["Bangor","Lewiston-Auburn","Portland"] },
  "Maryland": { abrev: "MD", ciudades: ["Annapolis","Baltimore","Cumberland Valley","Eastern Shore","Frederick","Western Maryland"] },
  "Massachusetts": { abrev: "MA", ciudades: ["Boston","Brockton","Cape Cod","Lowell","South Coast","Springfield","Worcester"] },
  "Michigan": { abrev: "MI", ciudades: ["Ann Arbor","Battle Creek","Central Michigan","Detroit","Flint","Grand Rapids","Holland","Jackson","Kalamazoo","Lansing","Monroe","Muskegon","Northern Michigan","Port Huron","Saginaw","Southwest Michigan","Upper Peninsula"] },
  "Minnesota": { abrev: "MN", ciudades: ["Bemidji","Brainerd","Duluth","Mankato","Minneapolis","Rochester","St. Cloud"] },
  "Mississippi": { abrev: "MS", ciudades: ["Biloxi","Hattiesburg","Jackson","Meridian","North Mississippi","Southwest Mississippi"] },
  "Missouri": { abrev: "MO", ciudades: ["Columbia","Joplin","Kansas City","Kirksville","Lake Of The Ozarks","Saint Louis","Southeast Missouri","Springfield","St Joseph"] },
  "Montana": { abrev: "MT", ciudades: ["Billings","Bozeman","Butte","Great Falls","Helena","Kalispell","Missoula"] },
  "Nebraska": { abrev: "NE", ciudades: ["Grand Island","Lincoln","North Platte","Omaha","Scottsbluff"] },
  "Nevada": { abrev: "NV", ciudades: ["Elko","Las Vegas","Reno","Virginia City"] },
  "New Hampshire": { abrev: "NH", ciudades: ["Concord","Dover","Manchester","Nashua"] },
  "New Jersey": { abrev: "NJ", ciudades: ["Central Jersey","Jersey Shore","North Jersey","South Jersey"] },
  "New Mexico": { abrev: "NM", ciudades: ["Albuquerque","Clovis","Farmington","Las Cruces","Roswell","Santa Fe"] },
  "New York": { abrev: "NY", ciudades: ["Albany","Binghamton","Bronx","Brooklyn","Buffalo","Catskills","Chautauqua","Elmira","Finger Lakes","Glens Falls","Hudson Valley","Ithaca","Long Island","Manhattan","Oneonta","Plattsburgh","Potsdam","Queens","Rochester","Staten Island","Syracuse","Twin Tiers","Utica","Watertown","Westchester"] },
  "North Carolina": { abrev: "NC", ciudades: ["Asheville","Boone","Charlotte","Eastern","Fayetteville","Greensboro","Hickory","High Point","Outer Banks","Raleigh","Raleigh-Durham","Wilmington","Winston-Salem"] },
  "North Dakota": { abrev: "ND", ciudades: ["Bismarck","Fargo","Grand Forks","Minot"] },
  "Ohio": { abrev: "OH", ciudades: ["Akron","Ashtabula","Athens","Cambridge","Chillicothe","Cincinnati","Cleveland","Columbus","Dayton","Findlay","Mansfield","Sandusky","Toledo","Tuscarawas County","Youngstown"] },
  "Oklahoma": { abrev: "OK", ciudades: ["Lawton","Norman","Oklahoma City","Stillwater","Tulsa"] },
  "Oregon": { abrev: "OR", ciudades: ["Bend","Corvallis","East Oregon","Eugene","Klamath Falls","Medford","Oregon Coast","Portland","Roseburg","Salem"] },
  "Pennsylvania": { abrev: "PA", ciudades: ["Allentown","Altoona","Chambersburg","Erie","Harrisburg","Lancaster","Meadville","Penn State","Philadelphia","Pittsburgh","Poconos","Reading","Scranton","Williamsport","York"] },
  "Rhode Island": { abrev: "RI", ciudades: ["Providence","Warwick"] },
  "South Carolina": { abrev: "SC", ciudades: ["Charleston","Columbia","Florence","Greenville","Hilton Head","Myrtle Beach"] },
  "South Dakota": { abrev: "SD", ciudades: ["Aberdeen","Pierre","Rapid City","Sioux Falls"] },
  "Tennessee": { abrev: "TN", ciudades: ["Chattanooga","Clarksville","Cookeville","Johnson City","Knoxville","Memphis","Nashville","Tri-Cities"] },
  "Texas": { abrev: "TX", ciudades: ["Abilene","Amarillo","Austin","Beaumont","Brownsville","College Station","Corpus Christi","Dallas","Del Rio","Denton","El Paso","Fort Worth","Galveston","Houston","Huntsville","Killeen","Laredo","Longview","Lubbock","Mcallen","Mid Cities","Odessa","San Antonio","San Marcos","Texarkana","Texoma","Tyler","Victoria","Waco","Wichita Falls"] },
  "Utah": { abrev: "UT", ciudades: ["Logan","Ogden","Provo","Salt Lake City","St. George"] },
  "Vermont": { abrev: "VT", ciudades: ["Burlington","Colchester","Essex"] },
  "Virginia": { abrev: "VA", ciudades: ["Charlottesville","Chesapeake","Danville","Fredericksburg","Hampton","Harrisonburg","Lynchburg","New River Valley","Newport News","Norfolk","Portsmouth","Richmond","Roanoke","Southwest Virginia","Suffolk","Virginia Beach"] },
  "Washington": { abrev: "WA", ciudades: ["Bellingham","Everett","Moses Lake","Mt. Vernon","Olympia","Pullman","Seattle","Spokane","Tacoma","Tri-Cities","Wenatchee","Yakima"] },
  "West Virginia": { abrev: "WV", ciudades: ["Charleston","Huntington","Martinsburg","Morgantown","Parkersburg","Southern West Virginia","Wheeling"] },
  "Wisconsin": { abrev: "WI", ciudades: ["Appleton","Eau Claire","Green Bay","Janesville","La Crosse","Madison","Milwaukee","Racine","Sheboygan","Wausau"] },
  "Wyoming": { abrev: "WY", ciudades: ["Casper","Cheyenne","Laramie"] }
};
